name: 'Install Python Dependencies'
description: 'Installs Python dependencies from requirements.txt'

runs:
  using: 'composite'
  steps:
    - name: Install on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        python3 -m pip install --upgrade pip --break-system-packages
        pip install -r requirements.txt --break-system-packages

    - name: Install on Windows
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
