name: Python Tests on Self-Hosted Runners

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-on-linux:
    name: Python Tests on Linux Runner
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip --break-system-packages
        pip install -r requirements.txt --break-system-packages

    - name: Run tests
      run: |
        mkdir -p test-reports
        pytest --junitxml=test-reports/results.xml

    - name: Upload test results as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results-linux
        path: test-reports/results.xml

  test-on-windows:
    name: Python Tests on Windows Runner
    runs-on: [self-hosted, windows]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Run tests
      run: |
        mkdir test-reports
        python -m pytest --junitxml=test-reports/results.xml

    - name: Upload test results as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results-windows
        path: test-reports/results.xml
